fix(actions): install gateway api required by linkerd
```
Error: The Gateway API CRDs must be installed prior to installing
Linkerd: https://gateway-api.sigs.k8s.io/guides/#installing-gateway-api
```