fix(charts): address test failures (#257)
Fix helm install error

```sh
Error: INSTALLATION FAILED:
resource ImagePolicy/flux-system/application-w24be83k50 not ready. status: InProgress, message: ImagePolicy generation is 1, but latest observed generation is -1
resource ImageRepository/flux-system/application-w24be83k50 not ready. status: InProgress, message: ImageRepository generation is 1, but latest observed generation is -1
```

This error occurred because the FluxCD ImagePolicy and -Repository
resources are not reconciled by the corresponding Flux controllers.
And therefore, their state won't be set to Ready, see for example
- https://fluxcd.io/flux/components/image/imagepolicies/#observed-generation

which causes `helm install` to failed because it's waiting for them.

Fix this by installing Flux into the Kind cluster
- https://fluxcd.io/flux/installation/#dev-install

And also make the `.spec.interval` available in `flux-image-policy`
- https://fluxcd.io/flux/components/image/imagepolicies/#interval

so that, it can be picked up faster during test run.

An other error is

```sh
Error: INSTALLATION FAILED:
Ingress.networking.k8s.io "dependency-track-oq1jlcou1p" is invalid: spec.rules[0].host: Invalid value: "127.0.0.1": must be a DNS name, not an IP address
```

which is fixed by setting the default ingress host value to `mms.eu`.