fix(scripts): fix linkerd install error in chart-test-prep
Install gateway api required by linkerd to fix the error

```
Error: The Gateway API CRDs must be installed prior to installing
Linkerd: https://gateway-api.sigs.k8s.io/guides/#installing-gateway-api
```