fix(scripts): fix linkerd install error in chart-test-prep (#199)
Install gateway api required by linkerd to fix the error

```
Error: The Gateway API CRDs must be installed prior to installing
Linkerd: https://gateway-api.sigs.k8s.io/guides/#installing-gateway-api
```

Also replace the deprecated linkerd install url based on the message
in the workflow run
```
*******************************************
* This script is deprecated and no longer *
* installs stable releases.               *
*                                         *
* The latest edge release has been        *
* installed. In the future, please use    *
*   run.linkerd.io/install-edge           *
* for this behavior.                      *
*                                         *
* For stable releases, please see         *
*  https://linkerd.io/releases/           *
*******************************************
```

See also
- https://linkerd.io/2-edge/getting-started/#step-1-install-the-cli

Lastly replace comments in script with workflow debug messages
- https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-a-debug-message