ci(actions): fix warnings on setup helm and python (#65)
Fixes warning in
- azure/setup-helm
  ```
  Error: [@octokit/auth-action] `GITHUB_TOKEN` variable is not set.
  ```
- actions/setup-python
  ```
  Neither 'python-version' nor 'python-version-file' inputs were supplied.
  ```

See for example the outputs
- https://github.com/MediaMarktSaturn/helm-charts/actions/runs/6692577288/job/18182051073?pr=62
for PR #97.

Required
- https://github.com/MediaMarktSaturn/helm-charts/pull/63
because Helm and Python versions setup with this change,
required chart-testing-actions >= `v2.6.0`.

Also adjust the changed files detection for ignored files changes.

See also:
- https://github.com/Azure/setup-helm
- https://github.com/actions/setup-python